import './globals.css'
import Nav from '@/components/BasicParts/Nav'
import { Poppins, Source_Code_Pro } from 'next/font/google'

const poppins = Poppins({
  variable: "--display-font",
  weight: ['400','600'],
  subsets: ['latin']
})
const sourceCodePro = Source_Code_Pro({
  // weight: ['400','600'],
  variable: "--body-font",
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>
      <body className={`${poppins.variable} ${sourceCodePro.className}`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
